name: isolates_example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter:
    sdk: flutter
  http: ^0.13.6
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
